/**
 * NirmanBook — Wardrobe Catalogue Import Data
 * Source: Wardrobe_Catalogue_Nirmanbook.pdf
 *
 * This file was generated by extracting every module image from the
 * catalogue PDF and visually reading each one's internal layout.
 *
 * ⚠️ IMPORTANT — READ BEFORE IMPORTING:
 * The `sections` array for each module is a best-effort visual read of
 * small thumbnail images (140x338px in the source PDF). Shelf counts,
 * drawer counts, and hanging-rod configuration are accurate for the
 * clearly-legible modules (01-12, corner units, accessory-tagged ones)
 * but should be spot-checked against the actual PDF for modules 13,
 * 15, 19, 33-40 specifically — these have denser/mixed layouts that
 * are harder to read at thumbnail resolution. Treat this as a strong
 * first draft, not a guaranteed-perfect transcription.
 *
 * SECTION SCHEMA (top → bottom, matches physical layout order):
 *   { type: "shelf", count: N }        — N open shelves stacked
 *   { type: "hanging", count: N }      — N hanging rods (1 = single rod
 *                                         zone, 2 = double/stacked rod)
 *   { type: "drawer", count: N }       — N stacked drawer fronts
 *   { type: "accessory", slot: "trouser-rack" | "jewellery-tray" |
 *            "accessory-tray" | "shoe-rack" }
 *                                       — an accessory insert occupying
 *                                         one section slot
 *   { type: "door", count: N }         — small cupboard doors (module 15)
 *
 * A module's `sections` array is what the compositional 3D renderer
 * should read to build up the module from primitives — see the
 * accompanying build prompt for how ModuleMesh.jsx should consume this.
 *
 * `accessoryEditable: true` on a module means the customer can swap
 * that module's accessory section for a different accessory type
 * (jewellery tray ↔ accessory tray ↔ trouser rack) during configuration,
 * and the 3D preview should re-render that section accordingly.
 */

export const wardrobeModules = [
  // ─── Shelf-only / basic hanging (01–12) ───
  {
    id: 'OW-SW-01',
    displayId: 'OW/SW 01',
    name: 'Open Shelving Unit',
    category: 'Shelves',
    availableIn: ['OW', 'SW'],
    sections: [{ type: 'shelf', count: 6 }],
    accessoryEditable: false,
    image: 'module-OW-SW-01.jpg',
  },

  {
    id: 'OW-SW-02',
    displayId: 'OW/SW 02',
    name: 'Full Double Hanging',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-02.jpg',
  },

  {
    id: 'OW-SW-03',
    displayId: 'OW/SW 03',
    name: 'Full Hanging with Base Shelf',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 1 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-03.jpg',
  },

  {
    id: 'OW-SW-04',
    displayId: 'OW/SW 04',
    name: 'Hanging with Shelf and Drawer',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 1 },
      { type: 'drawer', count: 1 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-04.jpg',
  },

  {
    id: 'OW-SW-05',
    displayId: 'OW/SW 05',
    name: 'Hanging with Triple Shelf',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 3 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-05.jpg',
  },

  {
    id: 'OW-SW-06',
    displayId: 'OW/SW 06',
    name: 'Hanging, Shelf and Drawer',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 2 },
      { type: 'drawer', count: 1 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-06.jpg',
  },

  {
    id: 'OW-SW-07',
    displayId: 'OW/SW 07',
    name: 'Hanging with Two Drawers',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 1 },
      { type: 'drawer', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-07.jpg',
  },

  {
    id: 'OW-SW-08',
    displayId: 'OW/SW 08',
    name: 'Hanging with Triple Drawer',
    category: 'Drawers',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'drawer', count: 3 },
      { type: 'shelf', count: 1 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-08.jpg',
  },

  {
    id: 'OW-SW-09',
    displayId: 'OW/SW 09',
    name: 'Hanging with Two Drawers (Alt)',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 1 },
      { type: 'drawer', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-09.jpg',
  },

  {
    id: 'OW-SW-10',
    displayId: 'OW/SW 10',
    name: 'Hanging with Four Drawers',
    category: 'Drawers',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'drawer', count: 4 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-10.jpg',
  },

  {
    id: 'OW-SW-11',
    displayId: 'OW/SW 11',
    name: 'Hanging with Four Drawers (Alt)',
    category: 'Drawers',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'drawer', count: 4 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-11.jpg',
  },

  {
    id: 'OW-12',
    displayId: 'OW 12',
    name: 'Hanging, Small Drawers and Shelves',
    category: 'Drawers',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'drawer', count: 2 },
      { type: 'shelf', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-12.jpg',
  },

  // ─── Mixed compartments (13–18) ───
  {
    id: 'OW-13',
    displayId: 'OW 13',
    name: 'Hanging with Mixed Storage',
    category: 'Specialty',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'drawer', count: 1 },
      { type: 'shelf', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-13.jpg',
  },

  {
    id: 'OW-SW-14',
    displayId: 'OW/SW 14',
    name: 'Hanging, Shelf and Two Drawers',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 1 },
      { type: 'drawer', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-14.jpg',
  },

  {
    id: 'OW-SW-15',
    displayId: 'OW/SW 15',
    name: 'Hanging with Cupboard Doors',
    category: 'Specialty',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'door', count: 2 },
      { type: 'shelf', count: 1 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-15.jpg',
  },

  {
    id: 'OW-16',
    displayId: 'OW 16',
    name: 'Hanging, Double Shelf and Drawer',
    category: 'Hanging',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 2 },
      { type: 'drawer', count: 1 },
    ],
    accessoryEditable: false,
    image: 'module-OW-16.jpg',
  },

  {
    id: 'OW-17',
    displayId: 'OW 17',
    name: 'Hanging, Shelf and Two Drawers (Alt)',
    category: 'Hanging',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 1 },
      { type: 'drawer', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-17.jpg',
  },

  {
    id: 'OW-18',
    displayId: 'OW 18',
    name: 'Hanging with Triple Drawer (Light)',
    category: 'Drawers',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'drawer', count: 3 },
    ],
    accessoryEditable: false,
    image: 'module-OW-18.jpg',
  },

  // ─── Drawer tower ───
  {
    id: 'OW-19',
    displayId: 'OW 19',
    name: 'Drawer Tower',
    category: 'Drawers',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 3 },
      { type: 'drawer', count: 3 },
    ],
    accessoryEditable: false,
    image: 'module-OW-19.jpg',
  },

  // ─── Accessory-tray / jewellery-tray variants (22–26) ───
  {
    id: 'OW-SW-22',
    displayId: 'OW/SW 22',
    name: 'Hanging with Accessory Tray',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'accessory-tray' },
      { type: 'drawer', count: 2 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-22.jpg',
  },

  {
    id: 'OW-SW-23',
    displayId: 'OW/SW 23',
    name: 'Hanging with Jewellery Tray',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'jewellery-tray' },
      { type: 'drawer', count: 2 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-23.jpg',
  },

  {
    id: 'OW-SW-24',
    displayId: 'OW/SW 24',
    name: 'Hanging with Jewellery Tray (Alt)',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'jewellery-tray' },
      { type: 'drawer', count: 2 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-24.jpg',
  },

  {
    id: 'OW-SW-25',
    displayId: 'OW/SW 25',
    name: 'Hanging with Accessory Tray (Alt)',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'accessory-tray' },
      { type: 'drawer', count: 2 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-25.jpg',
  },

  {
    id: 'OW-SW-26',
    displayId: 'OW/SW 26',
    name: 'Hanging with Accessory Tray and Drawers',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'accessory-tray' },
      { type: 'drawer', count: 3 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-26.jpg',
  },

  // ─── Trouser rack variants (27–30) ───
  {
    id: 'OW-SW-27',
    displayId: 'OW/SW 27',
    name: 'Hanging with Jewellery Tray and Drawers',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'jewellery-tray' },
      { type: 'drawer', count: 3 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-27.jpg',
  },

  {
    id: 'OW-SW-28',
    displayId: 'OW/SW 28',
    name: 'Hanging with Trouser Rack',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'trouser-rack' },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-28.jpg',
  },

  {
    id: 'OW-SW-29',
    displayId: 'OW/SW 29',
    name: 'Hanging with Trouser Rack (Alt)',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'trouser-rack' },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-29.jpg',
  },

  {
    id: 'OW-30',
    displayId: 'OW 30',
    name: 'Hanging with Trouser Rack and Shelves',
    category: 'Hanging',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'trouser-rack' },
      { type: 'shelf', count: 2 },
    ],
    accessoryEditable: true,
    image: 'module-OW-30.jpg',
  },

  // ─── Shoe storage (31–35) ───
  {
    id: 'OW-SW-31',
    displayId: 'OW/SW 31',
    name: 'Shoe Rack Tower',
    category: 'Shoe',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'shelf', count: 6 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-31.jpg',
  },

  {
    id: 'OW-SW-32',
    displayId: 'OW/SW 32',
    name: 'Shoe and Storage Shelves',
    category: 'Shoe',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'shelf', count: 6 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-32.jpg',
  },

  {
    id: 'OW-SW-33',
    displayId: 'OW/SW 33',
    name: 'Mixed Shelving with Shoe Storage',
    category: 'Shoe',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'shelf', count: 3 },
      { type: 'shelf', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-33.jpg',
  },

  {
    id: 'OW-SW-34',
    displayId: 'OW/SW 34',
    name: 'Hanging, Drawers and Shoe Shelf',
    category: 'Mixed',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'drawer', count: 2 },
      { type: 'shelf', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-34.jpg',
  },

  {
    id: 'OW-SW-35',
    displayId: 'OW/SW 35',
    name: 'Shelf, Drawer and Shoe Shelf',
    category: 'Mixed',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'shelf', count: 2 },
      { type: 'drawer', count: 1 },
      { type: 'shelf', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-35.jpg',
  },

  // ─── With iron/appliance shelf (36–40) ───
  {
    id: 'OW-36',
    displayId: 'OW 36',
    name: 'Appliance Shelf, Hanging and Drawers',
    category: 'Drawers',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'drawer', count: 4 },
    ],
    accessoryEditable: false,
    image: 'module-OW-36.jpg',
  },

  {
    id: 'OW-SW-37',
    displayId: 'OW/SW 37',
    name: 'Appliance Shelf, Hanging, Shelf and Drawers',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 1 },
      { type: 'drawer', count: 3 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-37.jpg',
  },

  {
    id: 'OW-38',
    displayId: 'OW 38',
    name: 'Appliance Shelf, Hanging and Split Drawers',
    category: 'Drawers',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'drawer', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-38.jpg',
  },

  {
    id: 'OW-39',
    displayId: 'OW 39',
    name: 'Appliance Shelf, Hanging and Split Storage',
    category: 'Specialty',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'drawer', count: 2 },
      { type: 'shelf', count: 2 },
    ],
    accessoryEditable: false,
    image: 'module-OW-39.jpg',
  },

  {
    id: 'OW-40',
    displayId: 'OW 40',
    name: 'Appliance Shelf, Split Drawer and Shelf Bays',
    category: 'Specialty',
    availableIn: ['OW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'drawer', count: 3 },
      { type: 'shelf', count: 3 },
    ],
    accessoryEditable: false,
    image: 'module-OW-40.jpg',
  },

  // ─── Wooden-shelf accessory variants (41–47) ───
  {
    id: 'OW-SW-41',
    displayId: 'OW/SW 41',
    name: 'Hanging, Shelf and Drawer',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 1 },
      { type: 'drawer', count: 1 },
    ],
    accessoryEditable: false,
    image: 'module-OW-SW-41.jpg',
  },

  {
    id: 'OW-SW-42',
    displayId: 'OW/SW 42',
    name: 'Hanging with Jewellery Tray (Wood Shelf)',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'jewellery-tray' },
      { type: 'drawer', count: 2 },
      { type: 'shelf', count: 1 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-42.jpg',
  },

  {
    id: 'OW-SW-43',
    displayId: 'OW/SW 43',
    name: 'Hanging with Jewellery Tray and Drawers (Wood Shelf)',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'jewellery-tray' },
      { type: 'drawer', count: 3 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-43.jpg',
  },

  {
    id: 'OW-SW-44',
    displayId: 'OW/SW 44',
    name: 'Hanging with Accessory Tray (Wood Shelf)',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'accessory-tray' },
      { type: 'drawer', count: 2 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-44.jpg',
  },

  {
    id: 'OW-SW-45',
    displayId: 'OW/SW 45',
    name: 'Hanging with Accessory Tray and Drawers (Wood Shelf)',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'accessory-tray' },
      { type: 'drawer', count: 3 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-45.jpg',
  },

  {
    id: 'OW-SW-46',
    displayId: 'OW/SW 46',
    name: 'Hanging with Jewellery Tray and Drawers (Wood Shelf, Alt)',
    category: 'Hanging',
    availableIn: ['OW', 'SW'],
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'accessory', slot: 'jewellery-tray' },
      { type: 'drawer', count: 3 },
    ],
    accessoryEditable: true,
    image: 'module-OW-SW-46.jpg',
  },

  {
    id: 'OW-SW-47',
    displayId: 'OW/SW 47',
    name: 'Full Open Shelving (Deep)',
    category: 'Shelves',
    availableIn: ['OW', 'SW'],
    sections: [{ type: 'shelf', count: 6 }],
    accessoryEditable: false,
    image: 'module-OW-SW-47.jpg',
  },
];

// ─── Corner Units — separate category, L-shaped geometry ───
export const cornerUnits = [
  {
    id: 'OW-20A',
    displayId: 'OW 20 A',
    name: 'Corner Unit 20A',
    category: 'Corner',
    availableIn: ['OW'],
    cornerVariant: 'A',
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 2 },
    ],
    accessoryEditable: false,
    image: 'corner-OW-20A.jpg',
  },

  {
    id: 'OW-20B',
    displayId: 'OW 20 B',
    name: 'Corner Unit 20B',
    category: 'Corner',
    availableIn: ['OW'],
    cornerVariant: 'B',
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 2 },
    ],
    accessoryEditable: false,
    image: 'corner-OW-20B.jpg',
  },

  {
    id: 'OW-21A',
    displayId: 'OW 21 A',
    name: 'Corner Unit 21A (Angled Door)',
    category: 'Corner',
    availableIn: ['OW'],
    cornerVariant: 'A',
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 1 },
    ],
    accessoryEditable: false,
    image: 'corner-OW-21A.jpg',
  },

  {
    id: 'OW-21B',
    displayId: 'OW 21 B',
    name: 'Corner Unit 21B (Angled Door)',
    category: 'Corner',
    availableIn: ['OW'],
    cornerVariant: 'B',
    sections: [
      { type: 'shelf', count: 1 },
      { type: 'hanging', count: 1 },
      { type: 'shelf', count: 2 },
    ],
    accessoryEditable: false,
    image: 'corner-OW-21B.jpg',
  },
];

// ─── Internal Colours — new catalog type ───
export const internalColours = [
  { id: 'white', name: 'White', hex: '#f2f1ec', image: 'colour-white.jpg' },
  { id: 'grey', name: 'Grey', hex: '#a9b0b3', image: 'colour-grey.jpg' },
  { id: 'twist-ivory', name: 'Twist Ivory', hex: '#d9d2c2', image: 'colour-twist-ivory.jpg' },
  { id: 'twist-grey', name: 'Twist Grey', hex: '#8f9086', image: 'colour-twist-grey.jpg' },
  {
    id: 'virginia-walnut',
    name: 'Virginia Walnut',
    hex: '#5c3a2e',
    image: 'colour-virginia-walnut.jpg',
  },
  {
    id: 'swiss-chestnut',
    name: 'Swiss Chestnut',
    hex: '#8c7c6b',
    image: 'colour-swiss-chestnut.jpg',
  },
  {
    id: 'iconic-chestnut',
    name: 'Iconic Chestnut',
    hex: '#4a3a30',
    image: 'colour-iconic-chestnut.jpg',
  },
];

// ─── Drawer Fascia — new catalog type (drawer front styles) ───
export const drawerFascia = [
  { id: 'akila', name: 'Akila', handleStyle: 'twin-pull', image: 'fascia-akila.jpg' },
  { id: 'nubia', name: 'Nubia', handleStyle: 'scoop-cutout', image: 'fascia-nubia.jpg' },
  { id: 'eugiene', name: 'Eugiene', handleStyle: 'bar-handle', image: 'fascia-eugiene.jpg' },
  { id: 'rebeka', name: 'Rebeka', handleStyle: 'bar-handle-wide', image: 'fascia-rebeka.jpg' },
  { id: 'carmen', name: 'Carmen', handleStyle: 'open-frame-pull', image: 'fascia-carmen.jpg' },
  { id: 'sofia', name: 'Sofia', handleStyle: 'open-frame-flush', image: 'fascia-sofia.jpg' },
  { id: 'xena-b', name: 'Xena B', handleStyle: 'recessed-edge', image: 'fascia-xena-b.jpg' },
  { id: 'xena-a', name: 'Xena A', handleStyle: 'recessed-edge-bar', image: 'fascia-xena-a.jpg' },
  {
    id: 'mandisa',
    name: 'Mandisa',
    handleStyle: 'scoop-cutout-offset',
    image: 'fascia-mandisa.jpg',
  },
];

// ─── Wardrobe Accessories — new catalog type, addable to accessoryEditable modules ───
export const wardrobeAccessories = [
  {
    id: 'side-mounted-hanger-rod',
    name: 'Side-mounted Hanger Rod',
    slotType: 'hanging',
    image: 'accessory-side-mounted-hanger-rod.jpg',
  },
  {
    id: 'top-mounted-hanger-rod',
    name: 'Top-mounted Hanger Rod',
    slotType: 'hanging',
    image: 'accessory-top-mounted-hanger-rod.jpg',
  },
  {
    id: 'jewellery-tray',
    name: 'Jewellery Tray',
    slotType: 'accessory',
    image: 'accessory-jewellery-tray.jpg',
  },
  {
    id: 'accessory-tray',
    name: 'Accessory Tray',
    slotType: 'accessory',
    image: 'accessory-accessory-tray.jpg',
  },
  {
    id: 'trouser-rack',
    name: 'Trouser Rack',
    slotType: 'accessory',
    image: 'accessory-trouser-rack.jpg',
  },
  { id: 'shoe-rack', name: 'Shoe Rack', slotType: 'shoe', image: 'accessory-shoe-rack.jpg' },
];

// ─── Shared spec info from the catalogue ───
export const catalogueSpecs = {
  baseMaterials: ['Particle Board', 'MDF', 'BWR', 'BWP'],
  heightOptionsMM: [1950, 2000, 2050, 2100, 2150, 2200, 2250, 2300, 2350, 2400],
};
